# docker-compose.yml
version: '3.8' # Specify Compose file version

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17 # Use the LTS image with JDK 17
    container_name: jenkins
    restart: unless-stopped # Restart the container unless manually stopped
    ports:
      - "8080:8080" # Map host port 8080 to container port 8080 (Jenkins UI)
      - "50000:50000" # Map host port 50000 to container port 50000 (for JNLP-based agents)
    volumes:
      - jenkins_home:/var/jenkins_home # Mount a named volume to persist Jenkins data
    environment:
      - TZ=Asia/Kolkata # Optional: Set your timezone (using India/Kolkata as an example based on your location)


volumes:
  jenkins_home: {} # Declare the named volume managed by Docker
